// Generated by: flutterfire configure --project=YOUR-APP-staging \
//   --out=lib/firebase_options/firebase_options_staging.dart
// Store the real output at ~/.secrets/firebase_template/staging/firebase_options.dart
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class StagingFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Platform not supported for Firebase.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_STAGING_ANDROID_API_KEY',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'YOUR-APP-staging',
    storageBucket: 'YOUR-APP-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_STAGING_IOS_API_KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'YOUR-APP-staging',
    storageBucket: 'YOUR-APP-staging.firebasestorage.app',
    iosBundleId: 'com.yourcompany.app.staging',
  );
}
